### ISSUE TITLE
react-flask-hello won't run backend right after installing flask-jwt-extended

### ISSUE THREAD

**Issue by UmiKami** [4GeeksAcademy/About-4Geeks-Academy#4220]
### Bug description

Installing flask-jwt-extended prevents the flask app from starting. There is no issues with the installation. But when you run `pipenv run start`, it throws the following error:

```
 Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/workspace/react-flask-hello/.venv/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/workspace/react-flask-hello/src/app.py", line 12, in <module>
    from api.admin import setup_admin
  File "/workspace/react-flask-hello/src/api/admin.py", line 5, in <module>
    from flask_admin.contrib.sqla import ModelView
  File "/workspace/react-flask-hello/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/workspace/react-flask-hello/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
    from flask_admin.contrib.sqla.tools import is_relationship
  File "/workspace/react-flask-hello/.venv/lib/python3.10/site-packages/flask_admin/contrib/sqla/tools.py", line 11, in <module>
    from sqlalchemy.ext.associationproxy import ASSOCIATION_PROXY
ImportError: cannot import name 'ASSOCIATION_PROXY' from 'sqlalchemy.ext.associationproxy' (/workspace/react-flask-hello/.venv/lib/python3.10/site-packages/sqlalchemy/ext/associationproxy.py)
```

### Steps to reproduce

1. On the terminal, type `pip install flask-jwt-extended`
2. On the terminal, start the backend by running `pipenv run start`
3. Backend does not start, error is thrown.

### Expected behavior

It should go ahead and start the backend and show me the addresses where I can connect to it, as well as it should open the simple browser.

### Anything else?

Here's the workspace snapshot where you can see the issue yourself: https://gitpod.io#snapshot/53fac7f2-f8f6-48cf-85cf-30a36dcd1d0d

**Comment by arnaldoperez** [comment]
This bug is caused by a problem with an update of sqlAlchemy that conflicts with flask. In the current version of the repo the sqlAlchemy version is fixed in the last version that worked instead of '*' for using the latest. I tried to check the snapshot to verify this but is not available. The fix was introduced recently so is probable that the error was produced in an older version of the boilerplate.
